version: 0.2

env:
  variables:
    REGION: ap-southeast-1
    REPOSITORY_NAME: hello-repo

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo Build started...
      - docker build -t $REPOSITORY_NAME .
      - docker tag $REPOSITORY_NAME:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing image...
      - docker push $REPOSITORY_URI:latest

artifacts:
  files:
    - appspec.yml
    - scripts/**/*